### ISSUE TITLE
Feature Request: Logfile support

### ISSUE THREAD

**Issue by sjcliffe** [lopter/lightsd#1]
I tried running lightsd with stderr redirected to a log file which works fine in the foreground but not in the background (-d) as it seems to close the stdio file descriptors. Would it be possible to add support via the command line to specify a log file location?

Thanks & great work!

**Comment by lopter** [comment]
Yes, I can see how that would be useful!

This shouldn't be too hard, I also had the idea of supporting syslog that might even be a better solution, what do you think?

**Comment by sjcliffe** [comment]
Syslog would work. If you provide the ability to specify a facility then the syslog config can be used to direct it to a specific file.

**Comment by lopter** [comment]
Cool, I'll look into that then!

**Comment by lopter** [comment]
Hey @sjcliffe, I just wanted to say that I probably won't do that before early October, depending on your use case [Supervisor](http://supervisord.org/) might be a temporary solution, it's an easy solution. It's packaged on most system otherwise it can be installed in a Python virtualenv.

**Comment by sjcliffe** [comment]
No problem @lopter - not really an issue, more of a nice to have in future.

**Comment by lopter** [comment]
@sjcliffe here is a [patch](https://raw.githubusercontent.com/lopter/lightsd-mq/9e49d3dafa6166a6f9fe00992ef3ec2481f1848f/add_syslog_support.patch) that adds syslog supports to lightsd, in case you wanna try it.

It seems to be working fine on Linux/BSD, logs didn't show up on OS X Yosemite, but I don't see why it wouldn't work, I'm too lazy to dig into the OS X settings.

I should release that soon, with packaging for OpenWRT and dpkg, before I start working on GH-5.
