### ISSUE TITLE
Doesn't work behind nginx proxy

### ISSUE THREAD

**Issue by ra100** [lopter/lightsd#11]
I want to use lightsd with nginx, so I can connect/send request from remote machine.
lightsd runs listening on socket, what I've set up in nginx config. I tried maybe every configuration combination, nothing worked. 
I tried it with `examples/lightsc.py`, here is script output:
```
Couldn't infer lightsd's runtime directory, is lightsd installed? ([Errno 2] No such file or directory: 'lightsd')
Trying build/socket...
Connecting to lightsd@tcp://192.168.150.7:8449
Connected to tcp://192.168.150.7:8449, use the variable c to interact with your bulbs:

>>> r = c.get_light_state("*")
>>> from pprint import pprint
>>> pprint(r)
```
When I try to run `c.get_light_state("*")`, it just hangs there an I need to kill process and lightsd doesn't show any connected clients.

Here is my nginx config, also with settings I tried to use.
```
upstream "lightsd" {
        server unix:/run/lightsd/socket;
}

server {
        listen 8449;
        server_name     192.168.150.7;

        location / {
#               proxy_set_header        Host                    $host;
#               proxy_set_header        Accept-Encoding         "";
#               proxy_set_header        X-Real-IP               $remote_addr;
#               proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
#               proxy_set_header        X-Forwarded-Proto       $scheme;
#               client_max_body_size    10m;
#               client_body_buffer_size 128k;
#               proxy_connect_timeout   90;
#               proxy_send_timeout      90;
#               proxy_read_timeout      90;
#               proxy_buffers           32 4k;
#               proxy_buffering         off;
#               proxy_redirect          off;
                proxy_pass              http://lightsd;
        }

}
```

Thanks for any help.

**Comment by digitalsushi** [comment]
The lightsd socket interface is a TCP interface, not HTTP.  You can configure it in nginx, but when lightsc.py connects to nginx, you're not saying anything nginx understands.  I know nginx has socket support, but it is for HTTP protocol.

Even if you were speaking HTTP to nginx, nginx would then not be speaking the JSON language that the lightsd socket expects.  You have a two layer onion of unrelated protocols.

**Comment by ra100** [comment]
Thanks, that was stupid of me to mix HTTP and TCP. Now I have it properly configured and it works.

**Comment by digitalsushi** [comment]
Cheers mate
