### ISSUE TITLE
Building on raspbian fails on signing dsc files

### ISSUE THREAD

**Issue by gerricom** [lopter/lightsd#17]
I'm currently trying to build lightsd on my RaspberryPi running the current raspbian-release [as described here.](http://lightsd.readthedocs.io/en/latest/installation.html#build-instructions-for-debian-based-systems-ubuntu-raspbian) Everything seems fine until lightsd should be signed:

```
Now signing changes and any dsc files...
 signfile lightsd_1.1.2-1.dsc Louis Opter <kalessin@kalessin.fr>
gpg: Verzeichnis `/home/pi/.gnupg' erzeugt
gpg: Neue Konfigurationsdatei `/home/pi/.gnupg/gpg.conf' erstellt
gpg: WARNUNG: Optionen in `/home/pi/.gnupg/gpg.conf' sind während dieses Laufes noch nicht wirksam
gpg: Schlüsselbund `/home/pi/.gnupg/secring.gpg' erstellt
gpg: Schlüsselbund `/home/pi/.gnupg/pubring.gpg' erstellt
gpg: übersprungen "Louis Opter <kalessin@kalessin.fr>": Geheimer Schlüssel ist nicht vorhanden
gpg: /tmp/debsign.oKNJz0Or/lightsd_1.1.2-1.dsc: clearsign failed: Geheimer Schlüssel ist nicht vorhanden
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1295:
running debsign failed
```

Seems that there is a dependency with your private gpg key, @lopter?

**Comment by lopter** [comment]
Hello, please use `debuild -uc -us`, that will fix your issue, I should have updated the documentation :s.

You can alternatively find (yet to be released) pre-build packages here: https://downloads.lightsd.io/debian/jessie/.

**Comment by khromov** [comment]
@lopter Documentation still not updated, just spent an hour trying to debug this before finding this thread. Please update it:
lightsd.readthedocs.io/en/latest/installation.html

**Comment by lopter** [comment]
Apologies for the time lost, fix on the way.
