### ISSUE TITLE
Discovery fails with "can't broadcast discovery packet: No route to host"

### ISSUE THREAD

**Issue by lopter** [lopter/lightsd#2]
On more pedantic systems (OpenBSD at the moment) with multiple interfaces the discovery will fail with this error.

This is because discovery packets aren't broadcasted properly: lightsd tries to send packets to 255.255.255.255 (`INADDR_BROADCAST`) which becomes ambiguous as soon as the system has multiple network interfaces.

There is two solutions for that, I'll probably implement both and make them mutually exclusive:

- the first solution is to let the user explicitly decide on which address or network interface lightsd should bind its discovery/broadcast socket, this will allow lightsd to broadcast packets using a valid (broadcast) address;
- the second solution will be for lightsd to discover all the network interfaces on the system and attempt to discover LIFX bulbs on each of them.

I'm looking at implementing the first solution soonish, no ETA for the second solution since it requires more work as network interface discovery is OS-specific.

**Comment by Magicking** [comment]
Any news on this ?

I'm made a temporary monkey patch (linux specific) to broadcast to every interface while the issue is resolved, patch is here https://github.com/Magicking/lightsd/commit/e3637e110a389453359a49920d8da23088dbad80

Cheers,

**Comment by lopter** [comment]
No real news, but @moonwatcher also complained about it so I'll address it, will see if I do that at 32C3 or after! Really wanna address GH-5 and reverse the new grouping API too.

Anyway, thank you so much for the patch it's helpful and motivating, need to look at it and figure out the portability bits, maybe I'll integrate it just for Linux since it's better than nothing.

**Comment by Magicking** [comment]
A nice evolution on their part would be to accept multicast (even without IGMP), that would allow to delegate some routing to the network.
