### ISSUE TITLE
What are the tags?

### ISSUE THREAD

**Issue by PascalMinder** [lopter/lightsd#22]
I was looking at the code, when I saw, that you spitted the target variable in the header into two pieces. One is the 6 byte large address and the other is the tags variable.

```
union {
        //! All targeted tags ORed together.
        uint64le_t  tags;
        //! Address of the targeted device.
        uint8_t     device_addr[LGTD_LIFX_ADDR_LENGTH];
} target;
```

But I can't find any information about the tags? What are they?

**Comment by lopter** [comment]
Hello Pascal,

The tags are used to group bulbs together, this is documented here:

- targeting: https://docs.lightsd.io/protocol.html#targeting-bulbs;
- tag/untag methods: https://docs.lightsd.io/protocol.html#tag.

Best

**Comment by lopter** [comment]
Hello Pascal,

The tags are used to group bulbs together, this is documented here:

- targeting: https://docs.lightsd.io/protocol.html#targeting-bulbs;
- tag/untag methods: https://docs.lightsd.io/protocol.html#tag.

Let me know if you have any question.

Best

**Comment by PascalMinder** [comment]
Thanks for your answer. That's exactly what I searched for. Somehow I must have missed the link to the doc :)

**Comment by lopter** [comment]
You're welcome!
