### ISSUE TITLE
New LIFX Product ID

### ISSUE THREAD

**Issue by avgays** [lopter/lightsd#23]
Hello Lopter,

Can you, please, add new LIFX product_id in lightsd/lifx/bulb.c from 
[https://lan.developer.lifx.com/docs/lifx-products](https://lan.developer.lifx.com/docs/lifx-products)
```
case 0x1B:
        return "LIFX A19";
case 0x1C:
        return "LIFX BR30";
case 0x1D:
        return "LIFX + A19";
case 0x1E:
        return "LIFX + BR30";
case 0x1F:
        return "LIFX Z";
```

**Comment by lopter** [comment]
Hello avgays,

Yes, I can do that for 1.2.1, I'm intending to make a new release soon, to iron out some issues with my CI/release pipeline.

Thank you
