### ISSUE TITLE
Wrong type for temperature value

### ISSUE THREAD

**Issue by PascalMinder** [lopter/lightsd#24]
I might be mistaken, but according to the official documentation, the value temperature in the response StateWifiInfo and StateHostInfo is an [signed 16-bit integer](https://lan.developer.lifx.com/docs/device-messages#section-statehostinfo-13). In your code it is an unsigned type (lgtd_lifx_packet_ip_state).

**Comment by lopter** [comment]
Hello Pascal,

I doubt that integer is signed, a range of values is probably encoded against `0 - (2**16 - 1)`.

If that was important I'd try to go look in the official app, but that field really isn't (important).

I don't care too much about the official docs, they didn't really exist when I wrote lightsd and I don't rely on them.
