### ISSUE TITLE
Is anybody working on an Home Assistant component?

### ISSUE THREAD

**Issue by mihalski** [lopter/lightsd#25]
Is anybody working on an alternative  Home Assistant component for Lifx lights which interfaces with lightsd instead of whatever 10 minute detecting horror show is being used currently?

**Comment by kylegordon** [comment]
Home-Assistant just migrated to aiolifx the other day, over at https://github.com/home-assistant/home-assistant/issues/6435

**Comment by lopter** [comment]
I'm glad to see lightsd being mentioned here!

@kylegordon, @mihalski you might have noticed the Python/asyncio lightsd client that I started to work on: https://github.com/lopter/lightsd/tree/1.2.1/clients/python/lightsc. Let me know if that's of interest for you and if you have any feedback about lightsd in general (e.g: missing things that would have made lightsd more relevant for a project like home-assistant).

Best
